### ISSUE TITLE
Support console pane

### ISSUE THREAD

**Issue by abhisekp** [ggoodman/plunker-run-plugin#8]
The console pane is very helpful in showing the console logs easily.
e.g. JSBin console pane

**Comment by ggoodman** [comment]
Hi @abhisekp, that is something that I would love to do but cannot do because of the very different strategy employed for running previews on Plunker vs previews on JSBin.

Plunker's previewing system is fully server-side and acts as if your project was statically hosted (after having done any pre-compilation as described [here](http://embed.plnkr.co/suu7Yg/preview)). Furthermore, I've decided to take the approach where Plunker will **not** transform your code at all. This means that what works on Plunker, will work on your `gh-pages` branch or on any static hosting solution (of course, modulo the compilation linked above).

As a consequence of this difference and this design decision, I cannot overload `console.log` which exists as a separate instance in the previewer `iframe`'s execution context. The previewer's execution context, being on a separate domain for security reasons, cannot be directly affected by code in the editor's context.
